import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, ArrowLeft, ArrowRight, BadgeCheck, ChevronDown, ClipboardList, CreditCard, FileText, LayoutDashboard, LockKeyhole, Plus, Search, Stethoscope, Users, Wallet } from 'lucide-react';
import '@fontsource/noto-sans/400.css';
import '@fontsource/noto-sans/600.css';
import '@fontsource/noto-sans/700.css';
import '@fontsource/noto-sans-bengali/400.css';
import '@fontsource/noto-sans-bengali/700.css';
import './style.css';

type State = {phase:'activation'|'setup'|'login'|'ready', clinic:string, user:{username:string,role:string,permissions:string[]}|null};
type Patient = {id:string,code:string,name:string,phone:string,gender:string,registered_at:string};
type Visit = {id:string,complaint:string,diagnosis:string,occurred_at:string,dentist_name_snapshot:string,treatment:string};
type Invoice = {id:string,number:string,patient_name_snapshot:string,code:string,total_poisha:number,paid_poisha:number,issued_at:string};
type Dentist = {id:string,name:string,designations:string};
const money=(p:number)=>`৳ ${(p/100).toLocaleString('en-BD',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
function amount(raw:string):number { if(!/^\d+(\.\d{1,2})?$/.test(raw)) throw new Error('Enter an amount with up to two decimal places.'); const [major,minor='']=raw.split('.'); const result=Number(major)*100+Number(minor.padEnd(2,'0')); if(!Number.isSafeInteger(result)) throw new Error('Amount is too large.'); return result; }
function errorMessage(error:unknown):string { const message=error instanceof Error ? error.message : 'Unable to complete the request. Try again.'; return message.replace(/^Error invoking remote method '[^']+': (Error: )?/, ''); }
const call=async <T,>(action:string,input:unknown={}):Promise<T>=>window.dentiva.request(action,input) as Promise<T>;
function App(){
  const [state,setState]=useState<State|null>(null),[page,setPage]=useState('dashboard'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[collapsed,setCollapsed]=useState(false);
  const [patients,setPatients]=useState<Patient[]>([]),[query,setQuery]=useState(''),[patient,setPatient]=useState<{patient:Patient&Record<string,string>,visits:Visit[]}|null>(null),[invoices,setInvoices]=useState<Invoice[]>([]),[dentists,setDentists]=useState<Dentist[]>([]),[stats,setStats]=useState<{patients:number,visits:number,finance:{billed:number,received:number}|null}|null>(null);
  const [pageIndex,setPageIndex]=useState(0),[form,setForm]=useState<Record<string,string>>({}),[items,setItems]=useState([{description:'',quantity:'1',price:''}]);
  const perms=state?.user?.permissions||[];
  const can=(permission:string)=>perms.includes(permission);
  const field=(key:string)=>(event:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>setForm(previous=>({...previous,[key]:event.target.value}));
  const run=async(task:()=>Promise<void>)=>{setBusy(true);setMessage('');try{await task();}catch(e){setMessage(errorMessage(e));}finally{setBusy(false);}};
  const refresh=()=>call<State>('status').then(setState).catch(e=>setMessage(errorMessage(e)));
  useEffect(()=>{refresh();},[]);
  useEffect(()=>{if(state?.phase!=='ready')return; if(page==='dashboard')call<typeof stats>('dashboard').then(setStats).catch(e=>setMessage(errorMessage(e))); if(page==='patients')call<Patient[]>('patients.list',{query,page:pageIndex}).then(setPatients).catch(e=>setMessage(errorMessage(e))); if(page==='invoices')call<Invoice[]>('invoices.list').then(setInvoices).catch(e=>setMessage(errorMessage(e)));},[state?.phase,page,query,pageIndex]);
  useEffect(()=>{if(state?.phase==='ready')call<Dentist[]>('dentists.list').then(setDentists).catch(()=>{});},[state?.phase]);
  useEffect(()=>{if(state?.phase!=='ready'||page!=='new-invoice')return;let active=true;const timer=setTimeout(()=>call<Patient[]>('patients.list',{query:form.patientSearch||'',page:0}).then(result=>{if(active)setPatients(result);}).catch(e=>{if(active)setMessage(errorMessage(e));}),180);return()=>{active=false;clearTimeout(timer);};},[state?.phase,page,form.patientSearch]);
  useEffect(()=>{const timer=setInterval(()=>refresh(),30000);return()=>clearInterval(timer);},[]);
  useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.ctrlKey&&e.shiftKey&&e.key.toLowerCase()==='p'&&can('patients.create')){e.preventDefault();setPage('new-patient');setForm({});} if(e.key==='Escape'&&patient)setPatient(null);};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[patient,state]);
  const navigate=(next:string)=>{setPage(next);setPatient(null);setMessage('');setForm({});};
  const submit=(e:React.FormEvent,task:()=>Promise<void>)=>{e.preventDefault();run(task);};
  const input=(key:string,label:string,required=false,type='text',placeholder='')=><label className="field"><span>{label}{required&&<b className="required"> *</b>}</span><input name={key} value={form[key]||''} onChange={field(key)} required={required} type={type} placeholder={placeholder}/></label>;
  const area=(key:string,label:string)=><label className="field"><span>{label}</span><textarea value={form[key]||''} onChange={field(key)} rows={3}/></label>;
  if(!state) return <div className="center"><div className="spinner" role="status" aria-label="Loading application"/></div>;
  if(state.phase!=='ready') return <div className="auth-layout"><div className="auth-art"><div className="brand-mark">D<span>+</span></div><p className="eyebrow">A BETTER WAY TO PRACTICE</p><h1>Care with clarity.<br/>Practice with confidence.</h1><p>Dentiva Pro brings your clinic’s daily work into focus — securely, locally, and beautifully.</p><div className="auth-bottom">PRIVATE BY DESIGN <span>•</span> BUILT FOR BANGLADESH</div></div><div className="auth-panel"><div className="auth-card"><div className="brand small"><div className="brand-mark">D<span>+</span></div><div>Dentiva <strong>Pro</strong></div></div><p className="eyebrow">{state.phase==='activation'?'01 / ACTIVATE':state.phase==='setup'?'02 / PERSONALIZE':'WELCOME BACK'}</p><h2>{state.phase==='activation'?'Activate your practice':state.phase==='setup'?'Set up your clinic':'Sign in to continue'}</h2><p className="subtle">{state.phase==='activation'?'Enter your one-time activation code to begin. This step works completely offline.':state.phase==='setup'?'Create your clinic profile and a secure owner account.':'Your clinic data stays on this computer.'}</p>{message&&<div className="alert" role="alert">{message}</div>}
  <form onSubmit={e=>submit(e,async()=>{if(state.phase==='activation')await call('activate',{code:form.code});else if(state.phase==='setup')await call('setup',{clinic:form.clinic,dentist:form.dentist,designation:form.designation,username:form.username,password:form.password});else await call('login',{username:form.username,password:form.password});setForm({});await refresh();})}>
    {state.phase==='activation'?input('code','Activation code',true,'password','Enter your code'):state.phase==='setup'?<>{input('clinic','Clinic / dental care name',true)}{input('dentist','Primary dentist',true)}{input('designation','Designation / qualification')}{input('username','Owner username',true)}{input('password','Owner password (at least 12 characters)',true,'password')}</>:<>{input('username','Username',true)}{input('password','Password',true,'password')}</>}
    <button className="primary full" disabled={busy}>{busy?'Please wait…':state.phase==='activation'?'Activate and continue':state.phase==='setup'?'Create clinic and owner account':'Sign in'} <ArrowRight size={17}/></button></form><p className="auth-foot">Dentiva Pro · Offline practice management</p></div></div></div>;
  const navGroups=[{label:'PRACTICE',items:[['dashboard','Dashboard',LayoutDashboard,'patients.view'],['patients','Patients',Users,'patients.view']]},{label:'BILLING',items:[['invoices','Invoices & payments',CreditCard,'billing.invoices.view']]},{label:'SYSTEM',items:[['about','About Dentiva Pro',BadgeCheck,'patients.view']]}] as const;
  return <div className="app-shell"><aside className={`sidebar ${collapsed?'collapsed':''}`}><div className="brand sidebar-brand"><div className="brand-mark">D<span>+</span></div>{!collapsed&&<div>Dentiva <strong>Pro</strong><small>CLINIC WORKSPACE</small></div>}</div><div className="side-content">{navGroups.map(group=><div className="nav-group" key={group.label}>{!collapsed&&<div className="nav-caption">{group.label}</div>}{group.items.filter(item=>can(item[3])).map(([id,label,Icon])=><button title={label} key={id} className={`nav-link ${page===id?'active':''}`} onClick={()=>navigate(id)}><Icon size={19} strokeWidth={1.8}/>{!collapsed&&<span>{label}</span>}</button>)}</div>)}</div><button className="collapse" onClick={()=>setCollapsed(!collapsed)} title={collapsed?'Expand sidebar':'Collapse sidebar'}><ChevronDown size={17} className={collapsed?'rotate':''}/>{!collapsed&&'Collapse sidebar'}</button></aside>
  <div className="workspace"><header className="topbar"><div className="clinic-head"><span className="clinic-avatar"><Stethoscope size={19}/></span><div><strong>{state.clinic}</strong><small>CLINIC WORKSPACE</small></div></div><div className="top-right"><span className="top-date">{new Intl.DateTimeFormat('en-BD',{timeZone:'Asia/Dhaka',day:'numeric',month:'long',year:'numeric'}).format(new Date())}</span><span className="top-divider"/><div className="user-badge"><span className="user-avatar">{state.user?.username.slice(0,1).toUpperCase()}</span><span><strong>{state.user?.username}</strong><small>{state.user?.role}</small></span></div><button className="icon-button" title="Lock application" aria-label="Lock application" onClick={()=>run(async()=>{await call('lock');await refresh();})}><LockKeyhole size={19}/></button></div></header><main className="main-content">{message&&<div className="alert" role="alert">{message}<button onClick={()=>setMessage('')} aria-label="Dismiss error">×</button></div>}
  {page==='dashboard'&&<><div className="page-heading"><div><div className="eyebrow">PRACTICE OVERVIEW</div><h1>Good day, {state.user?.username}.</h1><p>Here’s a clear view of your clinic today.</p></div>{can('patients.create')&&<button className="primary" onClick={()=>navigate('new-patient')}><Plus size={18}/> New patient</button>}</div><div className="hero-card"><div><span className="eyebrow light">YOUR PRACTICE, AT A GLANCE</span><h2>More time for the care that matters.</h2><p>Every patient story, visit and payment — thoughtfully organized in one place.</p><button onClick={()=>navigate('patients')} className="hero-action">Open patient directory <ArrowRight size={17}/></button></div><div className="hero-symbol" aria-hidden="true">D<span>+</span></div></div><div className="section-title"><h2>Overview</h2><span>Live clinic records</span></div><div className="stats-grid"><div className="stat-card"><div className="stat-icon teal"><Users size={20}/></div><span>Active patients</span><strong>{stats?.patients ?? '—'}</strong><small>Registered in your practice</small></div><div className="stat-card"><div className="stat-icon blue"><Activity size={20}/></div><span>Clinical visits</span><strong>{stats?.visits ?? '—'}</strong><small>Recorded encounters</small></div>{stats?.finance&&<><div className="stat-card"><div className="stat-icon amber"><FileText size={20}/></div><span>Total invoiced</span><strong>{money(stats.finance.billed)}</strong><small>Finalized invoices</small></div><div className="stat-card"><div className="stat-icon green"><Wallet size={20}/></div><span>Total received</span><strong>{money(stats.finance.received)}</strong><small>Recorded payments</small></div></>}</div><div className="section-title"><h2>Quick access</h2></div><div className="quick-grid"><button onClick={()=>navigate('patients')}><Users size={22}/><strong>Patient directory</strong><span>Find records and review visits</span><ArrowRight size={17}/></button>{can('billing.invoices.view')&&<button onClick={()=>navigate('invoices')}><CreditCard size={22}/><strong>Billing</strong><span>Invoices and payment history</span><ArrowRight size={17}/></button>}</div></>}
  {page==='patients'&&<><div className="page-heading"><div><div className="eyebrow">PRACTICE / PATIENTS</div><h1>Patients</h1><p>Every relationship starts with a clear patient record.</p></div>{can('patients.create')&&<button className="primary" onClick={()=>navigate('new-patient')}><Plus size={18}/> Register patient</button>}</div><section className="panel"><div className="panel-toolbar"><div className="search-box"><Search size={18}/><input aria-label="Search patients" placeholder="Search name, patient code or phone…" value={query} onChange={e=>{setQuery(e.target.value);setPageIndex(0);}}/></div><span className="subtle">Newest first · 30 per page</span></div>{patients.length?<div className="table-scroll"><table><thead><tr><th>Patient</th><th>Patient ID</th><th>Phone</th><th>Registered</th><th></th></tr></thead><tbody>{patients.map(p=><tr key={p.id}><td><span className="table-avatar">{p.name.slice(0,1).toUpperCase()}</span><strong>{p.name}</strong></td><td><span className="code">{p.code}</span></td><td>{p.phone||'—'}</td><td>{new Date(p.registered_at).toLocaleDateString('en-BD')}</td><td><button className="text-button" onClick={()=>run(async()=>{navigate('profile');setPatient(await call('patients.get',{id:p.id}));})}>View profile <ArrowRight size={15}/></button></td></tr>)}</tbody></table></div>:<div className="empty"><Users size={32}/><h3>{query?'No matching patients':'Your patient directory is ready'}</h3><p>{query?'Try a different name, code or phone.':'Register your first patient to start building their care history.'}</p>{!query&&can('patients.create')&&<button className="secondary" onClick={()=>navigate('new-patient')}>Register patient</button>}</div>}<div className="pagination"><button className="secondary" disabled={!pageIndex} onClick={()=>setPageIndex(pageIndex-1)}>Previous</button><span>Page {pageIndex+1}</span><button className="secondary" disabled={patients.length<30} onClick={()=>setPageIndex(pageIndex+1)}>Next</button></div></section></>}
  {page==='new-patient'&&<><div className="page-heading"><div><button className="back" onClick={()=>navigate('patients')}><ArrowLeft size={17}/> Patients</button><h1>Register a patient</h1><p>Build a reliable record for every step of their care.</p></div></div><form className="panel form-panel" onSubmit={e=>submit(e,async()=>{const id=await call<string>('patients.create',form);setPatient(await call('patients.get',{id}));setPage('profile');setForm({});})}><h2>Personal details</h2><div className="form-grid">{input('name','Full name',true)}{input('phone','Phone number')}{input('emergency_phone','Emergency phone')}{input('dob','Date of birth',false,'date')}{input('gender','Gender')}{input('blood_group','Blood group')}{input('address','Address')}</div><hr/><h2>Clinical background</h2><div className="form-grid">{area('presenting_problem','Presenting problem')}{area('allergies','Allergies')}{area('medical_history','Medical history')}{area('dental_history','Dental history')}{area('medications','Current medications')}{area('notes','Additional notes')}</div><div className="form-actions"><button type="button" className="secondary" onClick={()=>navigate('patients')}>Cancel</button><button className="primary" disabled={busy}>Save patient <ArrowRight size={17}/></button></div></form></>}
  {page==='profile'&&patient&&<><div className="page-heading"><div><button className="back" onClick={()=>navigate('patients')}><ArrowLeft size={17}/> Patient directory</button><div className="eyebrow">{patient.patient.code}</div><h1>{patient.patient.name}</h1><p>{patient.patient.phone||'No phone provided'} · Registered {new Date(patient.patient.registered_at).toLocaleDateString('en-BD')}</p></div>{can('clinical.visits.write')&&<button className="primary" onClick={()=>navigate('new-visit')}><Plus size={17}/> New visit</button>}</div><div className="profile-grid"><div className="panel detail-panel"><h2>Patient information</h2>{(['gender','blood_group','address','emergency_phone','presenting_problem','allergies','medical_history','dental_history','medications','notes'] as const).map(key=><div className="detail-row" key={key}><span>{key.replace(/_/g,' ')}</span><strong>{patient.patient[key]||'—'}</strong></div>)}</div><div className="panel detail-panel"><h2>Clinical visits <span className="count">{patient.visits.length}</span></h2>{patient.visits.length?patient.visits.map(v=><div className="visit-card" key={v.id}><small>{new Date(v.occurred_at).toLocaleString('en-BD')} · {v.dentist_name_snapshot}</small><strong>{v.complaint}</strong><p>{v.diagnosis||'No diagnosis entered'}</p>{v.treatment&&<span className="pill">{v.treatment}</span>}</div>):<div className="empty compact"><ClipboardList size={28}/><h3>No visits recorded</h3><p>Add an encounter to start this patient’s clinical history.</p></div>}</div></div></>}
  {page==='new-visit'&&patient&&<><div className="page-heading"><div><button className="back" onClick={()=>setPage('profile')}><ArrowLeft size={17}/> {patient.patient.name}</button><h1>New clinical visit</h1><p>Record the encounter without overwriting previous visits.</p></div></div><form className="panel form-panel" onSubmit={e=>submit(e,async()=>{await call('visits.create',{...form,patientId:patient.patient.id});setPatient(await call('patients.get',{id:patient.patient.id}));setPage('profile');setForm({});})}><label className="field"><span>Attending dentist *</span><select required value={form.dentistId||''} onChange={field('dentistId')}><option value="">Select a dentist</option>{dentists.map(d=><option value={d.id} key={d.id}>{d.name} {d.designations}</option>)}</select></label><div className="form-grid">{area('complaint','Chief complaint *')}{area('history','History')}{area('examination','Examination')}{area('diagnosis','Diagnosis')}{area('affected_teeth','Affected teeth')}{area('treatment','Treatment')}{area('procedure_text','Procedure')}{area('advice','Advice')}{area('notes','Clinical notes')}</div><div className="form-actions"><button type="button" className="secondary" onClick={()=>setPage('profile')}>Cancel</button><button className="primary" disabled={busy}>Save visit</button></div></form></>}
  {page==='invoices'&&<><div className="page-heading"><div><div className="eyebrow">BILLING / INVOICES</div><h1>Invoices & payments</h1><p>Clear billing, with a permanent record of every payment.</p></div>{can('billing.invoices.create')&&<button className="primary" onClick={()=>navigate('new-invoice')}><Plus size={17}/> New invoice</button>}</div><div className="panel">{invoices.length?<div className="table-scroll"><table><thead><tr><th>Invoice</th><th>Patient</th><th>Date</th><th>Total</th><th>Paid</th><th>Balance</th><th></th></tr></thead><tbody>{invoices.map(i=><tr key={i.id}><td className="code">{i.number}</td><td><strong>{i.patient_name_snapshot}</strong><small className="block">{i.code}</small></td><td>{new Date(i.issued_at).toLocaleDateString('en-BD')}</td><td>{money(i.total_poisha)}</td><td>{money(i.paid_poisha)}</td><td><span className={i.total_poisha-i.paid_poisha?'due':'paid'}>{money(i.total_poisha-i.paid_poisha)}</span></td><td>{i.total_poisha>i.paid_poisha&&can('billing.payments.record')&&<button className="text-button" onClick={()=>{setForm({invoiceId:i.id,invoiceNumber:i.number});setPage('payment');}}>Record payment <ArrowRight size={14}/></button>}</td></tr>)}</tbody></table></div>:<div className="empty"><FileText size={32}/><h3>No invoices yet</h3><p>Invoices you finalize will appear here.</p></div>}</div></>}
  {page==='new-invoice'&&<><div className="page-heading"><div><button className="back" onClick={()=>navigate('invoices')}><ArrowLeft size={17}/> Billing</button><h1>Create invoice</h1><p>Finalized invoice details are preserved for historical accuracy.</p></div></div><form className="panel form-panel" onSubmit={e=>submit(e,async()=>{await call('invoices.create',{patientId:form.patientId,items:items.map(i=>({description:i.description,quantity:Number(i.quantity),unit_poisha:amount(i.price)})),discount_poisha:amount(form.discount||'0')});navigate('invoices');setInvoices(await call('invoices.list'));})}><label className="field"><span>Find patient</span><input aria-label="Find patient by name, code or phone" placeholder="Type a name, code or phone…" value={form.patientSearch||''} onChange={e=>setForm(previous=>({...previous,patientSearch:e.target.value,patientId:''}))}/></label><label className="field"><span>Patient *</span><select required value={form.patientId||''} onChange={field('patientId')}><option value="">Select a patient</option>{patients.map(p=><option value={p.id} key={p.id}>{p.name} · {p.code}</option>)}</select></label><p className="helper">Searches all registered patients. Select a matching record before finalizing.</p><h2>Services</h2>{items.map((item,index)=><div className="invoice-item" key={index}><label className="field"><span>Description *</span><input required value={item.description} onChange={e=>setItems(items.map((i,n)=>n===index?{...i,description:e.target.value}:i))}/></label><label className="field"><span>Qty *</span><input required min="1" type="number" value={item.quantity} onChange={e=>setItems(items.map((i,n)=>n===index?{...i,quantity:e.target.value}:i))}/></label><label className="field"><span>Unit price (৳) *</span><input required inputMode="decimal" value={item.price} onChange={e=>setItems(items.map((i,n)=>n===index?{...i,price:e.target.value}:i))}/></label>{items.length>1&&<button type="button" className="text-button" onClick={()=>setItems(items.filter((_,n)=>n!==index))}>Remove</button>}</div>)}<button type="button" className="secondary" onClick={()=>setItems([...items,{description:'',quantity:'1',price:''}])}><Plus size={16}/> Add service</button><div className="form-grid">{input('discount','Discount (৳)',false,'text','0.00')}</div><div className="form-actions"><button type="button" className="secondary" onClick={()=>navigate('invoices')}>Cancel</button><button className="primary" disabled={busy}>Finalize invoice</button></div></form></>}
  {page==='payment'&&<><div className="page-heading"><div><button className="back" onClick={()=>navigate('invoices')}><ArrowLeft size={17}/> Billing</button><h1>Record payment</h1><p>Invoice {form.invoiceNumber} · payments are permanently recorded.</p></div></div><form className="panel form-panel narrow" onSubmit={e=>submit(e,async()=>{await call('payments.record',{invoiceId:form.invoiceId,amount_poisha:amount(form.amount),method:form.method,reference:form.reference||''});navigate('invoices');setInvoices(await call('invoices.list'));})}>{input('amount','Amount (৳)',true)}<label className="field"><span>Payment method *</span><select required value={form.method||''} onChange={field('method')}><option value="">Choose method</option>{['Cash','Bank','Card','bKash','Nagad','Rocket','Upay','Other'].map(m=><option key={m}>{m}</option>)}</select></label>{input('reference','Reference')}<div className="form-actions"><button type="button" className="secondary" onClick={()=>navigate('invoices')}>Cancel</button><button className="primary" disabled={busy}>Record payment</button></div></form></>}
  {page==='about'&&<><div className="page-heading"><div><div className="eyebrow">SYSTEM / ABOUT</div><h1>About Dentiva Pro</h1></div></div><div className="panel about"><div className="brand-mark large">D<span>+</span></div><h2>Dentiva Pro</h2><p>Offline dental practice management for Bangladesh.</p><div className="detail-row"><span>Developer</span><strong>Shohan Khan</strong></div><div className="detail-row"><span>Email</span><strong>helloiamshohan@gmail.com</strong></div><div className="detail-row"><span>Build</span><strong>Development · not for clinical use</strong></div></div></>}
  </main></div></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
